# SPDX-License-Identifier: GPL-2.0-only

rmnet_perf-$(CONFIG_RMNET_PERF) += rmnet_perf_config.o \
	rmnet_perf_core.o \
	rmnet_perf_opt.o \
	rmnet_perf_tcp_opt.o \
	rmnet_perf_udp_opt.o

obj-$(CONFIG_RMNET_PERF) += rmnet_perf.o
