# SPDX-License-Identifier: GPL-2.0-only

rmnet_shs-$(CONFIG_RMNET_SHS) += rmnet_shs_config.o \
	rmnet_shs_main.o \
	rmnet_shs_wq.o \
	rmnet_shs_freq.o \
	rmnet_shs_wq_mem.o \
	rmnet_shs_wq_genl.o

obj-$(CONFIG_RMNET_SHS) += rmnet_shs.o
